apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30003
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 30002

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rabbitmq-route
spec:
  to:
    kind: Service
    name: rabbitmq-nodeport
  port:
    targetPort: management
  tls:
    termination: passthrough
  wildcardPolicy: None
